'use client';

import React, { useCallback, useEffect, useState } from 'react';
import { AlertCircle, Archive, ChevronLeft, ChevronRight, Edit3, Eye, FileText, Plus, Send, X } from 'lucide-react';
import { apiRequest } from '../../../../lib/api';
import { getErrorMessage } from '../../../../lib/errors';

type ContentType = 'BANNER' | 'ARTICLE' | 'POPUP' | 'POLICY';
type ContentStatus = 'DRAFT' | 'PUBLISHED' | 'ARCHIVED';
interface ContentEntry { contentId: string; type: ContentType; slug: string; title: string; summary: string | null; body: string | null; imageUrl: string | null; linkUrl: string | null; status: ContentStatus; displayOrder: number; startsAt: string | null; endsAt: string | null; }
interface PagedContent { items: ContentEntry[]; total: number; page: number; limit: number; totalPages: number; }
interface FormState { type: ContentType; status: ContentStatus; slug: string; title: string; summary: string; body: string; imageUrl: string; linkUrl: string; displayOrder: string; startsAt: string; endsAt: string; }
const types: Record<ContentType, string> = { BANNER: 'Banner', ARTICLE: 'Bài viết', POPUP: 'Popup', POLICY: 'Chính sách' };
const statuses: Record<ContentStatus, string> = { DRAFT: 'Bản nháp', PUBLISHED: 'Đã xuất bản', ARCHIVED: 'Đã lưu trữ' };
const emptyForm: FormState = { type: 'ARTICLE', status: 'DRAFT', slug: '', title: '', summary: '', body: '', imageUrl: '', linkUrl: '', displayOrder: '0', startsAt: '', endsAt: '' };
const slugify = (value: string) => value.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/đ/g, 'd').replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
const localDate = (value: string | null) => value ? new Date(value).toISOString().slice(0, 16) : '';

export default function AdminContentPage() {
  const [result, setResult] = useState<PagedContent>({ items: [], total: 0, page: 1, limit: 20, totalPages: 0 });
  const [page, setPage] = useState(1); const [keyword, setKeyword] = useState(''); const [type, setType] = useState(''); const [status, setStatus] = useState('');
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(''); const [error, setError] = useState('');
  const [editing, setEditing] = useState<ContentEntry | null>(null); const [form, setForm] = useState<FormState>(emptyForm); const [formOpen, setFormOpen] = useState(false); const [preview, setPreview] = useState<ContentEntry | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(''); try { const params = new URLSearchParams({ page: String(page), limit: '20' }); if (keyword.trim()) params.set('keyword', keyword.trim()); if (type) params.set('type', type); if (status) params.set('status', status); setResult(await apiRequest<PagedContent>(`/content/admin/list?${params}`)); } catch (e: unknown) { setError(getErrorMessage(e, 'Không thể tải danh sách nội dung.')); } finally { setLoading(false); } }, [keyword, page, status, type]);
  useEffect(() => { queueMicrotask(() => { void load(); }); }, [load]);
  const openCreate = () => { setEditing(null); setForm(emptyForm); setFormOpen(true); };
  const openEdit = (item: ContentEntry) => { setEditing(item); setForm({ type: item.type, status: item.status, slug: item.slug, title: item.title, summary: item.summary || '', body: item.body || '', imageUrl: item.imageUrl || '', linkUrl: item.linkUrl || '', displayOrder: String(item.displayOrder), startsAt: localDate(item.startsAt), endsAt: localDate(item.endsAt) }); setFormOpen(true); };
  const save = async (event: React.FormEvent) => { event.preventDefault(); setSaving(true); setError(''); const emptyValue = editing ? null : undefined; const body = { ...form, summary: form.summary || emptyValue, body: form.body || emptyValue, imageUrl: form.imageUrl || emptyValue, linkUrl: form.linkUrl || emptyValue, displayOrder: Number(form.displayOrder) || 0, startsAt: form.startsAt ? new Date(form.startsAt).toISOString() : emptyValue, endsAt: form.endsAt ? new Date(form.endsAt).toISOString() : emptyValue }; try { await apiRequest(editing ? `/content/admin/${editing.contentId}` : '/content/admin', { method: editing ? 'PATCH' : 'POST', body: JSON.stringify(body) }); setFormOpen(false); setMessage(editing ? 'Đã cập nhật nội dung.' : 'Đã tạo nội dung.'); await load(); } catch (e: unknown) { setError(getErrorMessage(e, 'Không thể lưu nội dung.')); } finally { setSaving(false); } };
  const changeStatus = async (item: ContentEntry, next: ContentStatus) => { try { await apiRequest(`/content/admin/${item.contentId}`, { method: 'PATCH', body: JSON.stringify({ status: next }) }); setMessage(`Đã chuyển sang “${statuses[next]}”.`); await load(); } catch (e: unknown) { setError(getErrorMessage(e, 'Không thể đổi trạng thái.')); } };

  return <div className="space-y-6">
    <div className="flex flex-col justify-between gap-3 border-b border-border/60 pb-4 sm:flex-row sm:items-center"><div><h1 className="flex items-center gap-2 text-2xl font-extrabold"><FileText className="h-6 w-6 text-primary" /> Quản lý nội dung</h1><p className="mt-1 text-xs text-muted">Banner, bài viết, popup và chính sách hiển thị trên hệ thống.</p></div><button onClick={openCreate} className="flex items-center justify-center gap-2 rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground"><Plus className="h-4 w-4" /> Tạo nội dung</button></div>
    <form onSubmit={(e) => { e.preventDefault(); setPage(1); void load(); }} className="grid gap-3 rounded-xl border bg-card p-4 sm:grid-cols-3"><input value={keyword} onChange={(e) => setKeyword(e.target.value)} placeholder="Tìm tiêu đề hoặc slug..." className="rounded-lg border bg-background px-3 py-2 text-sm" /><select value={type} onChange={(e) => { setType(e.target.value); setPage(1); }} className="rounded-lg border bg-background px-3 text-sm"><option value="">Tất cả loại</option>{Object.entries(types).map(([v, l]) => <option key={v} value={v}>{l}</option>)}</select><select value={status} onChange={(e) => { setStatus(e.target.value); setPage(1); }} className="rounded-lg border bg-background px-3 text-sm"><option value="">Tất cả trạng thái</option>{Object.entries(statuses).map(([v, l]) => <option key={v} value={v}>{l}</option>)}</select></form>
    {message && <div className="rounded-xl border border-emerald-500/20 bg-emerald-500/10 p-4 text-sm text-emerald-800">{message}</div>}{error && <div className="flex gap-2 rounded-xl border border-red-500/20 bg-red-500/10 p-4 text-sm text-red-800"><AlertCircle className="h-5 w-5" />{error}</div>}
    <div className="overflow-hidden rounded-xl border bg-card"><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-xs"><thead className="border-b bg-secondary/40 uppercase"><tr><th className="p-4">Nội dung</th><th className="p-4">Loại</th><th className="p-4">Lịch hiển thị</th><th className="p-4">Trạng thái</th><th className="p-4 text-right">Thao tác</th></tr></thead><tbody className="divide-y">{loading ? <tr><td colSpan={5} className="p-10 text-center text-muted">Đang tải...</td></tr> : result.items.length === 0 ? <tr><td colSpan={5} className="p-10 text-center text-muted">Chưa có nội dung phù hợp.</td></tr> : result.items.map((item) => <tr key={item.contentId} className="hover:bg-secondary/20"><td className="p-4"><div className="font-bold">{item.title}</div><div className="font-mono text-[10px] text-muted">/{item.slug}</div></td><td className="p-4">{types[item.type]}</td><td className="p-4 text-muted"><div>{item.startsAt ? new Date(item.startsAt).toLocaleString('vi-VN') : 'Hiển thị ngay'}</div><div>{item.endsAt ? `đến ${new Date(item.endsAt).toLocaleString('vi-VN')}` : 'không giới hạn'}</div></td><td className="p-4"><span className="rounded-full bg-secondary px-2 py-1 font-bold">{statuses[item.status]}</span></td><td className="p-4"><div className="flex justify-end gap-1"><button onClick={() => setPreview(item)} className="rounded border p-2" title="Xem trước"><Eye className="h-4 w-4" /></button><button onClick={() => openEdit(item)} className="rounded border p-2" title="Sửa"><Edit3 className="h-4 w-4" /></button>{item.status !== 'PUBLISHED' && <button onClick={() => void changeStatus(item, 'PUBLISHED')} className="rounded border border-emerald-300 p-2 text-emerald-700" title="Xuất bản"><Send className="h-4 w-4" /></button>}{item.status === 'PUBLISHED' && <button onClick={() => void changeStatus(item, 'DRAFT')} className="rounded border border-amber-300 px-2 text-amber-700">Gỡ</button>}{item.status !== 'ARCHIVED' && <button onClick={() => void changeStatus(item, 'ARCHIVED')} className="rounded border p-2" title="Lưu trữ"><Archive className="h-4 w-4" /></button>}</div></td></tr>)}</tbody></table></div><div className="flex justify-between border-t p-3 text-xs text-muted"><span>{result.total} nội dung</span><div className="flex gap-2"><button disabled={page <= 1} onClick={() => setPage((v) => v - 1)} className="rounded border p-1 disabled:opacity-40"><ChevronLeft className="h-4 w-4" /></button><span>Trang {result.page}/{Math.max(result.totalPages, 1)}</span><button disabled={page >= result.totalPages} onClick={() => setPage((v) => v + 1)} className="rounded border p-1 disabled:opacity-40"><ChevronRight className="h-4 w-4" /></button></div></div></div>
    {formOpen && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/55 p-4"><form onSubmit={save} className="max-h-[92vh] w-full max-w-3xl overflow-auto rounded-2xl bg-card"><div className="sticky top-0 flex justify-between border-b bg-card p-5"><h2 className="font-bold">{editing ? 'Chỉnh sửa nội dung' : 'Tạo nội dung'}</h2><button type="button" onClick={() => setFormOpen(false)}><X className="h-5 w-5" /></button></div><div className="grid gap-4 p-5 sm:grid-cols-2"><Field label="Loại"><select value={form.type} onChange={(e) => setForm({ ...form, type: e.target.value as ContentType })} className="input">{Object.entries(types).map(([v, l]) => <option key={v} value={v}>{l}</option>)}</select></Field><Field label="Trạng thái"><select value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value as ContentStatus })} className="input">{Object.entries(statuses).map(([v, l]) => <option key={v} value={v}>{l}</option>)}</select></Field><Field label="Tiêu đề" wide><input required maxLength={255} value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value, slug: editing ? form.slug : slugify(e.target.value) })} className="input" /></Field><Field label="Slug" wide><input required pattern="[a-z0-9]+(?:-[a-z0-9]+)*" value={form.slug} onChange={(e) => setForm({ ...form, slug: e.target.value })} className="input font-mono" /></Field><Field label="Tóm tắt" wide><textarea rows={2} value={form.summary} onChange={(e) => setForm({ ...form, summary: e.target.value })} className="input" /></Field><Field label="Nội dung" wide><textarea rows={7} value={form.body} onChange={(e) => setForm({ ...form, body: e.target.value })} className="input" /></Field><Field label="URL hình ảnh"><input type="url" value={form.imageUrl} onChange={(e) => setForm({ ...form, imageUrl: e.target.value })} className="input" /></Field><Field label="URL điều hướng"><input type="url" value={form.linkUrl} onChange={(e) => setForm({ ...form, linkUrl: e.target.value })} className="input" /></Field><Field label="Bắt đầu"><input type="datetime-local" value={form.startsAt} onChange={(e) => setForm({ ...form, startsAt: e.target.value })} className="input" /></Field><Field label="Kết thúc"><input type="datetime-local" value={form.endsAt} onChange={(e) => setForm({ ...form, endsAt: e.target.value })} className="input" /></Field><Field label="Thứ tự"><input type="number" min="0" value={form.displayOrder} onChange={(e) => setForm({ ...form, displayOrder: e.target.value })} className="input" /></Field></div><div className="sticky bottom-0 flex justify-end gap-2 border-t bg-card p-4"><button type="button" onClick={() => setFormOpen(false)} className="rounded-lg bg-secondary px-4 py-2 text-sm">Hủy</button><button disabled={saving} className="rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground disabled:opacity-50">{saving ? 'Đang lưu...' : 'Lưu'}</button></div></form></div>}
    {preview && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/55 p-4"><article className="max-h-[85vh] w-full max-w-2xl overflow-auto rounded-2xl bg-card p-7"><div className="flex justify-between"><span className="rounded-full bg-primary/10 px-2 py-1 text-xs font-bold text-primary">{types[preview.type]}</span><button onClick={() => setPreview(null)}><X className="h-5 w-5" /></button></div><h2 className="mt-5 text-2xl font-extrabold">{preview.title}</h2>{preview.summary && <p className="mt-2 text-muted">{preview.summary}</p>}<div className="mt-5 whitespace-pre-wrap text-sm leading-7">{preview.body || 'Chưa có nội dung chi tiết.'}</div>{preview.imageUrl && <a href={preview.imageUrl} target="_blank" rel="noreferrer" className="mt-5 block break-all text-sm text-primary underline">Xem hình ảnh nội dung</a>}</article></div>}
  </div>;
}

function Field({ label, wide, children }: { label: string; wide?: boolean; children: React.ReactNode }) { return <label className={`text-xs font-semibold ${wide ? 'sm:col-span-2' : ''}`}>{label}<div className="mt-1 [&_.input]:w-full [&_.input]:rounded-lg [&_.input]:border [&_.input]:bg-background [&_.input]:p-2 [&_.input]:text-sm">{children}</div></label>; }
